title: Aashray Bavisa
logo: https://media.licdn.com/dms/image/D4E03AQE9sIX-MasfoQ/profile-displayphoto-shrink_800_800/0/1698198833294?e=1722470400&v=beta&t=lSTV84mpDwY64WhmnZGbFid2huhY7tNWXTNQulWtNKE
#description: text below image
# show_downloads: true
theme: jekyll-theme-minimal
